### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_2_vue_easy_toast

### ISSUE THREAD

**Issue by retrogradeMT** [noru/vue-easy-toast#10]
I'm attempting to use the toaster within a single file component, but I am getting the following error: 

    dcaReports.vue?a5fd:167 Uncaught (in promise) TypeError: __WEBPACK_IMPORTED_MODULE_2_vue_easy_toast___default(...) is not a function
    at VueComponent.eval (eval at <anonymous>  (main.js:1273), <anonymous>:173:79)

Here is my setup:

     <script>
    import { mapActions } from 'vuex'
    import Datepicker from 'vuejs-datepicker'
    import toast from 'vue-easy-toast'
       export default { ...
       ...
       ...
           methods: {
              detach: function(match, member){
                  this.$http.post('/detachCompany', ids ).then((response) => {
                    var data = response.data
                    if(data.status == 200){

                        toast('Hi, there!', {
                          id: 'my-toast',
                          className: ['my-toast', 'toast-warning'],
                          horizontalPosition: 'right',
                          verticalPosition: 'top',
                          duration: 3000,
                          mode: 'queue',
                        })

                    }
                   

                }, (response) => {
                    //gah!! Error

                });
        },

Am I missing something?

**Comment by noru** [comment]
hi @retrogradeMT , this is a vue plugin, so you have to "use" it beforehand, usually in your entry.js or index.js

// before start
import Toast from 'vue-easy-toast'
Vue.use(Toast)

**Comment by retrogradeMT** [comment]
Oh well, that's embarrassing.   I'm not why I didn't understand that immediately.    Thank you!
