### ISSUE TITLE
Object.assign is not a function in old/unsupported browser

### ISSUE THREAD

**Issue by raychenfj** [noru/vue-easy-toast#12]
@noru 

Thanks for your plugin.
I use vue-easy-toast in wechat development, but I got the error "Object.assign is not a function" when I open my page in wechat windows pc client.

Thought you miss the babel-plugin-transform-runtime in you webpack config, so the Object.assign is not polyfilled in your dist file

**Comment by noru** [comment]
@raychenfj Thanks for reporting this issue and sent a PR along with it. I'll verify it asap.

**Comment by noru** [comment]
Fixed in v0.2.6. Tested with IE11.
