### ISSUE TITLE
queue is not working

### ISSUE THREAD

**Issue by onerciller** [noru/vue-easy-toast#14]
Hi mode:queue is not working, what could be reason it ?

**Comment by noru** [comment]
hi @onerciller , could you please be more specific? I just [tried](https://noru.github.io/vue-easy-toast/example/index.html) with chrome/safari and the queue mode is fine.

**Comment by onerciller** [comment]
for instance I tried it from here https://noru.github.io/vue-easy-toast/example/index.html I selected queue but it did not work

**Comment by noru** [comment]
I think we have a misunderstand here. On queue mode, if you toast 2 messages sequentially, the latter one will wait until the first one reaches its "duration", then show its content. The demo link shows the same behavior.  

I bet you expect a different behavior like a message box stack of some sort. That's not a support feature of this plugin.
