### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by nilsi** [noru/vue-easy-toast#19]
Trying to use this library in my project but getting the following:
```
W20170510-23:52:23.009(9)? (STDERR) ../projectdir/node_modules/vue-easy-toast/src/EasyToast.vue:1
W20170510-23:52:23.009(9)? (STDERR) (function (exports, require, module, __filename, __dirname) { <template>
W20170510-23:52:23.010(9)? (STDERR)                                                               ^
W20170510-23:52:23.010(9)? (STDERR) 
W20170510-23:52:23.011(9)? (STDERR) SyntaxError: Unexpected token <
W20170510-23:52:23.011(9)? (STDERR)     at exports.runInThisContext (vm.js:53:16)
W20170510-23:52:23.012(9)? (STDERR)     at Module._compile (module.js:373:25)
W20170510-23:52:23.012(9)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170510-23:52:23.013(9)? (STDERR)     at Module.load (module.js:343:32)
W20170510-23:52:23.013(9)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170510-23:52:23.013(9)? (STDERR)     at Module.require (module.js:353:17)
W20170510-23:52:23.013(9)? (STDERR)     at require (internal/module.js:12:17)
```
Its Meteor + Vue project. I installed by `npm install vue-easy-toast --save` and added 
```
import Toast from 'vue-easy-toast'
Vue.use(Toast) 
```
to my `main.js`

Is the problem that this runs outside of my Vue environment or something like that? Thanks for any help on this.

**Comment by noru** [comment]
Hi @nilsi thanks for reporting. 
I'm kinda busy for a couple of days, so I could not get back to you soon enough. 

My suggestion is to fallback to previous version and give it a shot, since there was a major release last time.

Apology.

**Comment by noru** [comment]
The reason why this error occurred is the `.vue` file is not proper "[vueify](https://github.com/vuejs/vueify)". 

However, as you can see in my `package.json`, the default import goes to:
`"main": "dist/vue-easy-toast.min.js"`

I don't know how you end up importing `.vue` file directly, which you should not (it won't work), but to fix your module resolve configuration would help I think.
