### ISSUE TITLE
Styling Issue

### ISSUE THREAD

**Issue by stevepop** [noru/vue-easy-toast#2]
Hi, thanks for the nice work on this component. I have an issue with the styling. I followed your instructions on adding my own styling but it seems because the vue-easy-toast styling is inline, it keeps overriding my own styles. It only works only if I add !important to my styles which I don't really want to do.
This is how my toast.scss looks like;
```
.et-wrapper {
  &.toast-default {
    color: #ff0000;
    background: $brand-primary;
  }

  &.toast-success {
    background: $panel_green_color;
  }

  &.toast-notice {
    background: $brand-info;
  }

  &.toast-danger {
    background: $brand-danger;
  }

  &.tast-warning {
    background: $brand-warning;
  }
}
```
I then call the toast like below;
```
methods: {
            getMessage(type) {
                console.log('Settings updated: ' + type);
                Vue.toast(type + ' Settings updated successfully ', {
                  className: ['toast-success'],
                  duration: 2000
                })
            }
        }
```
But on display, I still see the default styles rendered. The style console shows inline style over-riding  my custom styles.

Is this an issue or something else I am supposed to add?
Thanks!

**Comment by noru** [comment]
@stevepop Thanks for the feedback. Indeed it is an issue. I have removed 'scoped' attribute in style block therefore default style won't be like this `.et-wrapper[hash_str]`. I think your style won't be overridden anymore, please try update to v0.1.2.

**Comment by stevepop** [comment]
@noru, thanks for your quick response. Unfortunately, I was unable to test the styling as it seems there something wrong with v0.1.2 as my components no longer worked and I was getting the error, 'Vue is not defined' in the console. I thought it was a problem with my code but when I rolled back to v0.1.0, everything worked normally, except of course for the styling issue which was supposed to have been fixed in v0.1.2.

**Comment by noru** [comment]
@stevepop Sorry, Steve, for the lousy experience. That is because I left a piece of dirty code in it. It is removed now in 0.1.3.

Looking forward to your confirmation about this styling issue.

**Comment by stevepop** [comment]
Hi @noru, I can confirm the styles work and I can now remove all my ! tags. Don't worry about the experience, I am happy to assist in improving the component. One last question, Does the 'parent' parameter work? I have the following markup in my template;
```
<div class="pull-right">
         <div id="toast-container"></div>
</div>
```
Then made the toast as follows;
```
Vue.toast("Prediction points successfully generated", {
        parent: '#toast-container',
        className: ['toast-success'],
         mode: 'queue'
 })
```
I did this because I wanted to change the default position of the toast message to the top right of my pages rather than the default bottom. So far, this has not worked as I can see the toast is still being displayed in the "easy-toast-default" ID.

Other than this, everything works as expected.

**Comment by noru** [comment]
@stevepop I'm still trying to figure out a proper way of positioning content within a parent. As of now, due to the current style of 'et-wrapper': 
```
position: fixed;
top: 80%;
```
, no matter which parent you choose, the position is fixed at the center-bottom of the window.

"Position option" is in my todo list in regards of 5-7 points (combination of left/right/top/bottom/center) on screen, your top-right is included. If your concern is about position refer to 'window', it should be fine to customize your style with something like `top: 10%; left:10%; transform: translateX(0);` to overwrite above.

I'll close this issue, open another one and keep you posted.

Thanks!
