### ISSUE TITLE
TS2345: Argument of type 'typeof ".../vue-easy-toast/types/index"' is not assignable to parameter of type 'PluginObject<{}> | PluginFunction<{}>'

### ISSUE THREAD

**Issue by gpuma** [noru/vue-easy-toast#24]
I get this error on line 2 trying to use  ´Toast´ in Vue, using TypeScript:

boot.ts:
```
import Toast from 'vue-easy-toast'
Vue.use(Toast);
```
Adding ´@ts-ignore´ removes compile time error but not runtime one.

Versions:
"typescript": "^2.2.1",
"vue": "^2.2.2",
"vue-easy-toast": "^1.0.4",

**Comment by noru** [comment]
Can you try cast it before `Vue.use`?
This component is not written in TS and by default exports the built file, so there shouldn't be any "runtime" error unless the Vue itself had some breaking changes. The example running on Vue 2.5.x works fine.
